PDOT = float(PDOT)
PRI = float(PRI)
PUST = float(PUST)
AUST = float(AUST)
APT = float(APT)
ADOT = float(ADOT)
ATT = float(ATT)
AQT = float(AQT)
APWT = float(APWT)
APAT = float(APAT)
GQ = float(GQ)
SQ = float(SQ)
PSQ = float(PSQ)
RQ = float(RQ)
OTBF = float(OTBF)
CMT = float(CMT)
PMT = float (PMT)
BLT = float(BLT)
STT = float(STT)
#HIGHER THE BETTER CALCULATIONS 
A = APT/PBT 
AE = AUBT/PBT 
TE = APT/(APT+ADOT)
WE = APWT/APAT 
UE = APT/AUBT
E = PRI*PQ/APT 
FTQ = GQ/PQF 
QBR = (GQ+RQ)/PQ
WE = APWT/APAT 
#lOWER THE BETTER CALCULATIONS 
SeR = AUST/AUPT 
SeR_inv = 1/SeR 
BL = BLT/PBT 
BL_inv = 1/BL 
ST = STT/PBT
ST_inv = 1/ST 
SQR = SQ/PSQ 
SQR_inv = 1/SQR 
SR = SQ/PQ
SR_inv = 1/SR
RR = RQ/PQ 
RR_inv = 1/RR 
FR = 1 - (PQF/PQ)
FR_inv = 1/FR 
CMR = CMT/PMT
CMR_inv = 1/CMR